#!/usr/bin/env bash
set -e

WORKSPACE="${AMR_TOPOLOGY_WS:-$HOME/Downloads/Topology_Graph_test-main}"

cd "$WORKSPACE"
source /opt/ros/humble/setup.bash
source "$WORKSPACE/install/setup.bash"

exec ros2 launch amr_topology turtlebot_mission.launch.py "$@"
