frame_id: map

nodes:
  loading:
    x: 2.4713807106018066
    y: -2.628671169281006
    yaw: 0.0
    type: loading_zone

  intersection_1:
    x: 2.442805051803589
    y: -0.015692830085754395
    yaw: 0.0
    type: intersection

  a_entry:
    x: 1.2001334428787231
    y: -0.001835942268371582
    yaw: 0.0
    type: area_entry

  b_entry:
    x: 1.1759474277496338
    y: -1.0073925256729126
    yaw: 0.0
    type: area_entry

  a_leader_slot:
    x: -0.06747579574584961
    y: 0.007548093795776367
    yaw: 0.0
    type: stationing_slot

  b_leader_slot:
    x: 0.005939602851867676
    y: -1.005650281906128
    yaw: 0.0
    type: stationing_slot

  charger_front:
    x: 0.10498535633087158
    y: -2.760960578918457
    yaw: 0.0
    type: charger

  charger_entry:
    x: 0.14896941184997559
    y: -1.9904364347457886
    yaw: 0.0
    type: charger_entry

  standby_1:
    x: 0.0
    y: 0.0
    yaw: 0.0
    type: standby

edges:
  - from: loading
    to: intersection_1
    bidirectional: true
    speed_limit: 0.18

  - from: intersection_1
    to: a_entry
    bidirectional: true
    speed_limit: 0.18

  - from: a_entry
    to: a_leader_slot
    bidirectional: true
    speed_limit: 0.10

  - from: a_entry
    to: b_entry
    bidirectional: true
    speed_limit: 0.12

  - from: b_entry
    to: b_leader_slot
    bidirectional: true
    speed_limit: 0.10

  - from: b_entry
    to: intersection_1
    bidirectional: true
    speed_limit: 0.12

  - from: b_entry
    to: charger_entry
    bidirectional: true
    speed_limit: 0.10

  - from: loading
    to: charger_entry
    bidirectional: true
    speed_limit: 0.10

  - from: charger_entry
    to: charger_front
    bidirectional: true
    speed_limit: 0.05

  - from: intersection_1
    to: standby_1
    bidirectional: true
    speed_limit: 0.10
